#!/user/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Nonetallt\Jinitialize\JinitializeApplication;

$app = new JinitializeApplication(__DIR__);

/* Register vendor plugins */
$app->registerPlugins(__DIR__.'/vendor/nonetallt/jinitialize-core/bootstrap/cache/plugins.php');

/* Register local commands and procedures */
$app->getContainer()->addPlugin('local');
$app->registerCommands('local', []);
$app->registerProcedures('local', [], __DIR__.'/procedures');

$app->run();
