#!/user/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Nonetallt\Jinitialize\JinitializeApplication;

$app = new JinitializeApplication(__DIR__);

/* Register vendor plugins */
$app->registerPlugins(__DIR__.'/boostrap/cache/plugins.php');

/* Register local comamnds and procedures */
$app->getContainer()->addPlugin('core');
$app->registerCommands('core', []);
$app->registerProcedures('core', [], __DIR__.'/procedures');

$app->run();
